//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAndDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BHSI_ACCOR_FINANCE_DATA_SHATRU_test
    {
        public string RECORD_ID { get; set; }
        public string QuarterName { get; set; }
        public string MeasureType { get; set; }
        public string YYYY { get; set; }
        public string QQ { get; set; }
        public string CountryName { get; set; }
        public string ProductLineName { get; set; }
        public string Net_Premiums_Written { get; set; }
        public string Net_Premiums_Earned { get; set; }
        public string Other_Income { get; set; }
        public string Losses_Incurred { get; set; }
        public string Commission_Paid { get; set; }
        public string Acquisition_DAC { get; set; }
        public string Acusiition_DAC___Prior { get; set; }
        public string Acq__post_DAC { get; set; }
        public string Direct_Expenses { get; set; }
        public string GAAP_Income { get; set; }
        public string Inception_to_Date { get; set; }
        public string Operating_Expenses { get; set; }
        public string Losses_Paid { get; set; }
        public string Loss_Case_Reserves { get; set; }
        public string Loss_IBNR { get; set; }
        public string Allocated_Expenses_Pd { get; set; }
        public string Loss_Expense_Case_Reserves { get; set; }
        public string Expense_IBNR_Reserves { get; set; }
        public string Loss_Expenses_Incurred { get; set; }
        public string ULAE_Pd { get; set; }
        public string ULAE_Reserves { get; set; }
        public string ULAE_Incurred { get; set; }
        public string Premium_Based_Exp__Paid { get; set; }
        public string Commission_Accrual { get; set; }
        public string Premium_Based_Exp__Accrual { get; set; }
        public string Operating_Expenses_Allocated { get; set; }
    }
}
