//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BHSI_FINANCEEntities : DbContext
    {
        public BHSI_FINANCEEntities()
            : base("name=BHSI_FINANCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STG_ETL_Parameters> STG_ETL_Parameters { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<BHSI_ACCOR_FINANCE_DATA> BHSI_ACCOR_FINANCE_DATA { get; set; }
        public virtual DbSet<dimMeasure> dimMeasures { get; set; }
        public virtual DbSet<dimMeasure_20160909> dimMeasure_20160909 { get; set; }
        public virtual DbSet<dimMeasure_ISA_20160812> dimMeasure_ISA_20160812 { get; set; }
        public virtual DbSet<dimMeasureSubGroup> dimMeasureSubGroups { get; set; }
        public virtual DbSet<dimMeasureSubGroup_20160909> dimMeasureSubGroup_20160909 { get; set; }
        public virtual DbSet<dimPage> dimPages { get; set; }
        public virtual DbSet<dimProduct> dimProducts { get; set; }
        public virtual DbSet<DIMPRODUCT_20160909> DIMPRODUCT_20160909 { get; set; }
        public virtual DbSet<dimproduct_bkp_28102016> dimproduct_bkp_28102016 { get; set; }
        public virtual DbSet<dimProduct_ISA_20160812> dimProduct_ISA_20160812 { get; set; }
        public virtual DbSet<dimQtr> dimQtrs { get; set; }
        public virtual DbSet<DimQtr_bkp> DimQtr_bkp { get; set; }
        public virtual DbSet<dimRegion> dimRegions { get; set; }
        public virtual DbSet<dimRegion_20160909> dimRegion_20160909 { get; set; }
        public virtual DbSet<dimRegion_ISA_20160812> dimRegion_ISA_20160812 { get; set; }
        public virtual DbSet<dimReportMaster> dimReportMasters { get; set; }
        public virtual DbSet<dimSubProduct> dimSubProducts { get; set; }
        public virtual DbSet<EXCLUSION_MEASURE> EXCLUSION_MEASURE { get; set; }
        public virtual DbSet<group_rights> group_rights { get; set; }
        public virtual DbSet<group_rights_mapper> group_rights_mapper { get; set; }
        public virtual DbSet<Group> groups { get; set; }
        public virtual DbSet<RejectActualData> RejectActualDatas { get; set; }
        public virtual DbSet<RejectAdjustmentData> RejectAdjustmentDatas { get; set; }
        public virtual DbSet<RejectBudgetData> RejectBudgetDatas { get; set; }
        public virtual DbSet<STG_ACTUALS> STG_ACTUALS { get; set; }
        public virtual DbSet<stg_actuals_20160627> stg_actuals_20160627 { get; set; }
        public virtual DbSet<STG_ACTUALS_20160722> STG_ACTUALS_20160722 { get; set; }
        public virtual DbSet<STG_ACTUALS_20161021> STG_ACTUALS_20161021 { get; set; }
        public virtual DbSet<STG_ACTUALS_BKP_20170209> STG_ACTUALS_BKP_20170209 { get; set; }
        public virtual DbSet<STG_ACTUALS_preDiv1000> STG_ACTUALS_preDiv1000 { get; set; }
        public virtual DbSet<STG_ACTUALS_Travel> STG_ACTUALS_Travel { get; set; }
        public virtual DbSet<STG_ACTUALS_US_NA_ISA> STG_ACTUALS_US_NA_ISA { get; set; }
        public virtual DbSet<STG_ADJUSTMENTS> STG_ADJUSTMENTS { get; set; }
        public virtual DbSet<STG_ADJUSTMENTS_20161116> STG_ADJUSTMENTS_20161116 { get; set; }
        public virtual DbSet<STG_ADJUSTMENTS_ISA> STG_ADJUSTMENTS_ISA { get; set; }
        public virtual DbSet<STG_BUDGET> STG_BUDGET { get; set; }
        public virtual DbSet<stg_budget_20160627> stg_budget_20160627 { get; set; }
        public virtual DbSet<STG_BUDGET_20160719> STG_BUDGET_20160719 { get; set; }
        public virtual DbSet<STG_BUDGET_BKP_20170209> STG_BUDGET_BKP_20170209 { get; set; }
        public virtual DbSet<stg_budget_Travel> stg_budget_Travel { get; set; }
        public virtual DbSet<stg_comments> stg_comments { get; set; }
        public virtual DbSet<stg_comments_isa> stg_comments_isa { get; set; }
        public virtual DbSet<STG_COMMENTS_ISA_20160812> STG_COMMENTS_ISA_20160812 { get; set; }
        public virtual DbSet<STG_ETL_Logs> STG_ETL_Logs { get; set; }
        public virtual DbSet<STG_ETL_Parameters_BKP_20170209> STG_ETL_Parameters_BKP_20170209 { get; set; }
        public virtual DbSet<STG_FINANCIALS> STG_FINANCIALS { get; set; }
        public virtual DbSet<stg_Headcount> stg_Headcount { get; set; }
        public virtual DbSet<TMP_Actuals> TMP_Actuals { get; set; }
        public virtual DbSet<TMP_Actuals_BKP_20170209> TMP_Actuals_BKP_20170209 { get; set; }
        public virtual DbSet<TMP_ADJUSTMENTS> TMP_ADJUSTMENTS { get; set; }
        public virtual DbSet<TMP_Budget> TMP_Budget { get; set; }
        public virtual DbSet<BHSI_ACCOR_FINANCE_DATA_Adi> BHSI_ACCOR_FINANCE_DATA_Adi { get; set; }
        public virtual DbSet<BHSI_ACCOR_FINANCE_DATA_SHATRU> BHSI_ACCOR_FINANCE_DATA_SHATRU { get; set; }
        public virtual DbSet<BHSI_ACCOR_FINANCE_DATA_SHATRU_test> BHSI_ACCOR_FINANCE_DATA_SHATRU_test { get; set; }
        public virtual DbSet<dimReportList> dimReportLists { get; set; }
        public virtual DbSet<VW_ADJUSTMENTREPORT> VW_ADJUSTMENTREPORT { get; set; }
        public virtual DbSet<vw_calc_Acquisition_Expense> vw_calc_Acquisition_Expense { get; set; }
        public virtual DbSet<vw_calc_Acquisition_Expenses_Incurred> vw_calc_Acquisition_Expenses_Incurred { get; set; }
        public virtual DbSet<vw_calc_DAC_Adjustment> vw_calc_DAC_Adjustment { get; set; }
        public virtual DbSet<vw_calc_GAAP_Income> vw_calc_GAAP_Income { get; set; }
        public virtual DbSet<vw_calc_Loss_Expenses_Incurred> vw_calc_Loss_Expenses_Incurred { get; set; }
        public virtual DbSet<vw_calc_Losses_Incurred> vw_calc_Losses_Incurred { get; set; }
        public virtual DbSet<vw_calc_Total_Loss_Incurred> vw_calc_Total_Loss_Incurred { get; set; }
        public virtual DbSet<vw_calc_Total_Operating_Expense> vw_calc_Total_Operating_Expense { get; set; }
        public virtual DbSet<vw_calc_ULAE_Incurred> vw_calc_ULAE_Incurred { get; set; }
        public virtual DbSet<vw_calc_Unearned_Premium> vw_calc_Unearned_Premium { get; set; }
        public virtual DbSet<vw_calc_UW_Expenses_Incurred> vw_calc_UW_Expenses_Incurred { get; set; }
    
        [DbFunction("BHSI_FINANCEEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[BHSI_FINANCEEntities].[Split](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        [DbFunction("BHSI_FINANCEEntities", "ufnQtrList")]
        public virtual IQueryable<ufnQtrList_Result> ufnQtrList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnQtrList_Result>("[BHSI_FINANCEEntities].[ufnQtrList]()");
        }
    
        public virtual int USP_ACCOR_POP_HISTRICAL_DATA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_ACCOR_POP_HISTRICAL_DATA");
        }
    
        public virtual int USP_AccordionJob(string p_ProcessType, string p_QtrLabel)
        {
            var p_ProcessTypeParameter = p_ProcessType != null ?
                new ObjectParameter("p_ProcessType", p_ProcessType) :
                new ObjectParameter("p_ProcessType", typeof(string));
    
            var p_QtrLabelParameter = p_QtrLabel != null ?
                new ObjectParameter("p_QtrLabel", p_QtrLabel) :
                new ObjectParameter("p_QtrLabel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_AccordionJob", p_ProcessTypeParameter, p_QtrLabelParameter);
        }
    
        public virtual ObjectResult<USP_GET_Accordion_Parameters_Result> USP_GET_Accordion_Parameters(string p_ETlJobName)
        {
            var p_ETlJobNameParameter = p_ETlJobName != null ?
                new ObjectParameter("p_ETlJobName", p_ETlJobName) :
                new ObjectParameter("p_ETlJobName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_Accordion_Parameters_Result>("USP_GET_Accordion_Parameters", p_ETlJobNameParameter);
        }
    
        public virtual ObjectResult<USP_GET_FINANCE_DATA_Result> USP_GET_FINANCE_DATA(string vCountryName, string vProductLineName)
        {
            var vCountryNameParameter = vCountryName != null ?
                new ObjectParameter("vCountryName", vCountryName) :
                new ObjectParameter("vCountryName", typeof(string));
    
            var vProductLineNameParameter = vProductLineName != null ?
                new ObjectParameter("vProductLineName", vProductLineName) :
                new ObjectParameter("vProductLineName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_FINANCE_DATA_Result>("USP_GET_FINANCE_DATA", vCountryNameParameter, vProductLineNameParameter);
        }
    
        public virtual int USP_INS_ACCRUAL(Nullable<System.DateTime> pQtr, string pRegionName, string pProductLineName)
        {
            var pQtrParameter = pQtr.HasValue ?
                new ObjectParameter("pQtr", pQtr) :
                new ObjectParameter("pQtr", typeof(System.DateTime));
    
            var pRegionNameParameter = pRegionName != null ?
                new ObjectParameter("pRegionName", pRegionName) :
                new ObjectParameter("pRegionName", typeof(string));
    
            var pProductLineNameParameter = pProductLineName != null ?
                new ObjectParameter("pProductLineName", pProductLineName) :
                new ObjectParameter("pProductLineName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_ACCRUAL", pQtrParameter, pRegionNameParameter, pProductLineNameParameter);
        }
    
        public virtual int USP_INS_ACCRUALPRIOR(Nullable<System.DateTime> pQtr, string pRegionName, string pProductLineName)
        {
            var pQtrParameter = pQtr.HasValue ?
                new ObjectParameter("pQtr", pQtr) :
                new ObjectParameter("pQtr", typeof(System.DateTime));
    
            var pRegionNameParameter = pRegionName != null ?
                new ObjectParameter("pRegionName", pRegionName) :
                new ObjectParameter("pRegionName", typeof(string));
    
            var pProductLineNameParameter = pProductLineName != null ?
                new ObjectParameter("pProductLineName", pProductLineName) :
                new ObjectParameter("pProductLineName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_ACCRUALPRIOR", pQtrParameter, pRegionNameParameter, pProductLineNameParameter);
        }
    
        public virtual int USP_INS_ProcessLog(Nullable<int> p_JobID, string p_ProcessType, string p_ProcessStatus, string p_ProcessLogMessage, Nullable<int> p_Inserted_Rows, Nullable<int> p_Processed_Rows, Nullable<int> p_Updated_Rows, Nullable<int> p_Reject_Rows, string p_LogUser)
        {
            var p_JobIDParameter = p_JobID.HasValue ?
                new ObjectParameter("p_JobID", p_JobID) :
                new ObjectParameter("p_JobID", typeof(int));
    
            var p_ProcessTypeParameter = p_ProcessType != null ?
                new ObjectParameter("p_ProcessType", p_ProcessType) :
                new ObjectParameter("p_ProcessType", typeof(string));
    
            var p_ProcessStatusParameter = p_ProcessStatus != null ?
                new ObjectParameter("p_ProcessStatus", p_ProcessStatus) :
                new ObjectParameter("p_ProcessStatus", typeof(string));
    
            var p_ProcessLogMessageParameter = p_ProcessLogMessage != null ?
                new ObjectParameter("p_ProcessLogMessage", p_ProcessLogMessage) :
                new ObjectParameter("p_ProcessLogMessage", typeof(string));
    
            var p_Inserted_RowsParameter = p_Inserted_Rows.HasValue ?
                new ObjectParameter("p_Inserted_Rows", p_Inserted_Rows) :
                new ObjectParameter("p_Inserted_Rows", typeof(int));
    
            var p_Processed_RowsParameter = p_Processed_Rows.HasValue ?
                new ObjectParameter("p_Processed_Rows", p_Processed_Rows) :
                new ObjectParameter("p_Processed_Rows", typeof(int));
    
            var p_Updated_RowsParameter = p_Updated_Rows.HasValue ?
                new ObjectParameter("p_Updated_Rows", p_Updated_Rows) :
                new ObjectParameter("p_Updated_Rows", typeof(int));
    
            var p_Reject_RowsParameter = p_Reject_Rows.HasValue ?
                new ObjectParameter("p_Reject_Rows", p_Reject_Rows) :
                new ObjectParameter("p_Reject_Rows", typeof(int));
    
            var p_LogUserParameter = p_LogUser != null ?
                new ObjectParameter("p_LogUser", p_LogUser) :
                new ObjectParameter("p_LogUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INS_ProcessLog", p_JobIDParameter, p_ProcessTypeParameter, p_ProcessStatusParameter, p_ProcessLogMessageParameter, p_Inserted_RowsParameter, p_Processed_RowsParameter, p_Updated_RowsParameter, p_Reject_RowsParameter, p_LogUserParameter);
        }
    
        public virtual ObjectResult<USP_PRIORREPORT_Result> USP_PRIORREPORT(Nullable<System.DateTime> pQtr)
        {
            var pQtrParameter = pQtr.HasValue ?
                new ObjectParameter("pQtr", pQtr) :
                new ObjectParameter("pQtr", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_PRIORREPORT_Result>("USP_PRIORREPORT", pQtrParameter);
        }
    
        public virtual int USP_PRIORS(Nullable<System.DateTime> pQtr)
        {
            var pQtrParameter = pQtr.HasValue ?
                new ObjectParameter("pQtr", pQtr) :
                new ObjectParameter("pQtr", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_PRIORS", pQtrParameter);
        }
    
        public virtual ObjectResult<USP_Processed_RejectedRows_Result> USP_Processed_RejectedRows()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Processed_RejectedRows_Result>("USP_Processed_RejectedRows");
        }
    
        public virtual ObjectResult<USP_Processed_RejectionReason_BKP_Result> USP_Processed_RejectionReason_BKP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Processed_RejectionReason_BKP_Result>("USP_Processed_RejectionReason_BKP");
        }
    
        public virtual ObjectResult<Nullable<int>> USP_Rejected_Rows_Count(Nullable<int> p_JobId)
        {
            var p_JobIdParameter = p_JobId.HasValue ?
                new ObjectParameter("p_JobId", p_JobId) :
                new ObjectParameter("p_JobId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_Rejected_Rows_Count", p_JobIdParameter);
        }
    
        public virtual ObjectResult<USP_ReportList_Result> USP_ReportList(Nullable<System.DateTime> pQtr)
        {
            var pQtrParameter = pQtr.HasValue ?
                new ObjectParameter("pQtr", pQtr) :
                new ObjectParameter("pQtr", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ReportList_Result>("USP_ReportList", pQtrParameter);
        }
    
        public virtual int USP_SEND_MAIL(Nullable<int> p_JOBID, string p_ProcessType, Nullable<int> p_Processed_Rows, Nullable<int> p_Inserted_Rows, Nullable<int> p_Updated_Rows, Nullable<int> p_Reject_Rows, string p_PROFILE_NAME, string p_RECIPIENTS, string p_SUBJECT)
        {
            var p_JOBIDParameter = p_JOBID.HasValue ?
                new ObjectParameter("p_JOBID", p_JOBID) :
                new ObjectParameter("p_JOBID", typeof(int));
    
            var p_ProcessTypeParameter = p_ProcessType != null ?
                new ObjectParameter("p_ProcessType", p_ProcessType) :
                new ObjectParameter("p_ProcessType", typeof(string));
    
            var p_Processed_RowsParameter = p_Processed_Rows.HasValue ?
                new ObjectParameter("p_Processed_Rows", p_Processed_Rows) :
                new ObjectParameter("p_Processed_Rows", typeof(int));
    
            var p_Inserted_RowsParameter = p_Inserted_Rows.HasValue ?
                new ObjectParameter("p_Inserted_Rows", p_Inserted_Rows) :
                new ObjectParameter("p_Inserted_Rows", typeof(int));
    
            var p_Updated_RowsParameter = p_Updated_Rows.HasValue ?
                new ObjectParameter("p_Updated_Rows", p_Updated_Rows) :
                new ObjectParameter("p_Updated_Rows", typeof(int));
    
            var p_Reject_RowsParameter = p_Reject_Rows.HasValue ?
                new ObjectParameter("p_Reject_Rows", p_Reject_Rows) :
                new ObjectParameter("p_Reject_Rows", typeof(int));
    
            var p_PROFILE_NAMEParameter = p_PROFILE_NAME != null ?
                new ObjectParameter("p_PROFILE_NAME", p_PROFILE_NAME) :
                new ObjectParameter("p_PROFILE_NAME", typeof(string));
    
            var p_RECIPIENTSParameter = p_RECIPIENTS != null ?
                new ObjectParameter("p_RECIPIENTS", p_RECIPIENTS) :
                new ObjectParameter("p_RECIPIENTS", typeof(string));
    
            var p_SUBJECTParameter = p_SUBJECT != null ?
                new ObjectParameter("p_SUBJECT", p_SUBJECT) :
                new ObjectParameter("p_SUBJECT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SEND_MAIL", p_JOBIDParameter, p_ProcessTypeParameter, p_Processed_RowsParameter, p_Inserted_RowsParameter, p_Updated_RowsParameter, p_Reject_RowsParameter, p_PROFILE_NAMEParameter, p_RECIPIENTSParameter, p_SUBJECTParameter);
        }
    
        public virtual int USP_TEST_JSON(string regionLabel)
        {
            var regionLabelParameter = regionLabel != null ?
                new ObjectParameter("RegionLabel", regionLabel) :
                new ObjectParameter("RegionLabel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_TEST_JSON", regionLabelParameter);
        }
    
        public virtual int USP_TEST_XMLROOT(string regionLabel)
        {
            var regionLabelParameter = regionLabel != null ?
                new ObjectParameter("RegionLabel", regionLabel) :
                new ObjectParameter("RegionLabel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_TEST_XMLROOT", regionLabelParameter);
        }
    
        public virtual int USP_TEST_XMLSPLIT(string regionLabel)
        {
            var regionLabelParameter = regionLabel != null ?
                new ObjectParameter("RegionLabel", regionLabel) :
                new ObjectParameter("RegionLabel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_TEST_XMLSPLIT", regionLabelParameter);
        }
    
        public virtual int USP_TRUNC_CRT_TMPTables(string p_ProcessType)
        {
            var p_ProcessTypeParameter = p_ProcessType != null ?
                new ObjectParameter("p_ProcessType", p_ProcessType) :
                new ObjectParameter("p_ProcessType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_TRUNC_CRT_TMPTables", p_ProcessTypeParameter);
        }
    
        public virtual int USP_TRUNCATE_STAGE_TABLES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_TRUNCATE_STAGE_TABLES");
        }
    
        public virtual ObjectResult<USP_GET_FINANCE_DATA_SH_Result> USP_GET_FINANCE_DATA_SH(string vCountryName, string vProductLineName)
        {
            var vCountryNameParameter = vCountryName != null ?
                new ObjectParameter("vCountryName", vCountryName) :
                new ObjectParameter("vCountryName", typeof(string));
    
            var vProductLineNameParameter = vProductLineName != null ?
                new ObjectParameter("vProductLineName", vProductLineName) :
                new ObjectParameter("vProductLineName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_FINANCE_DATA_SH_Result>("USP_GET_FINANCE_DATA_SH", vCountryNameParameter, vProductLineNameParameter);
        }
    }
}
