//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAndDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BHSI_ACCOR_FINANCE_DATA
    {
        public int RECORD_ID { get; set; }
        public string QuarterName { get; set; }
        public string MeasureType { get; set; }
        public int YYYY { get; set; }
        public string QQ { get; set; }
        public string CountryName { get; set; }
        public string ProductLineName { get; set; }
        public Nullable<decimal> Net_Premiums_Written { get; set; }
        public Nullable<decimal> Net_Premiums_Earned { get; set; }
        public Nullable<decimal> Other_Income { get; set; }
        public Nullable<decimal> Losses_Incurred__IL_LAE_ { get; set; }
        public Nullable<decimal> Commission_Paid__Acquisition_Expenses_ { get; set; }
        public Nullable<decimal> Acquisition_DAC { get; set; }
        public Nullable<decimal> Acquisition_DAC___Prior { get; set; }
        public Nullable<decimal> Acq__post_DAC { get; set; }
        public Nullable<decimal> GAAP_Income { get; set; }
        public Nullable<decimal> Inception_to_Date { get; set; }
        public Nullable<decimal> Losses_Paid { get; set; }
        public Nullable<decimal> Loss_Case_Reserves { get; set; }
        public Nullable<decimal> Loss_IBNR { get; set; }
        public Nullable<decimal> Allocated_Expenses_Pd { get; set; }
        public Nullable<decimal> Loss_Expense_Case_Reserves { get; set; }
        public Nullable<decimal> Expense_IBNR_Reserves { get; set; }
        public Nullable<decimal> Loss_Expenses_Incurred { get; set; }
        public Nullable<decimal> ULAE_Pd { get; set; }
        public Nullable<decimal> ULAE_Reserves { get; set; }
        public Nullable<decimal> ULAE_Incurred { get; set; }
        public Nullable<decimal> Premium_Based_Exp__Paid { get; set; }
        public Nullable<decimal> Commission_Accrual { get; set; }
        public Nullable<decimal> Premium_Based_Exp__Accrual { get; set; }
        public Nullable<decimal> Operating_Expenses_Allocated { get; set; }
        public Nullable<decimal> Operating_Expenses_Direct { get; set; }
        public Nullable<decimal> Operating_Exp_DAC { get; set; }
        public Nullable<decimal> Operating_Exp_post_DAC { get; set; }
        public Nullable<decimal> GAAP_Income___FD { get; set; }
        public Nullable<decimal> Inception_to_Date___FD { get; set; }
        public Nullable<decimal> Unearned_Premium_Change { get; set; }
        public Nullable<decimal> Other_U_W_Expense_Paid { get; set; }
        public Nullable<decimal> U_W_Expense_Reserves { get; set; }
        public Nullable<decimal> Agents_Balances { get; set; }
        public Nullable<decimal> Investment_in_Travel___Assist { get; set; }
    }
}
