//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class dimMeasureSubGroup
    {
        public int RowID_ { get; set; }
        public Nullable<short> MeasureSubGroupId { get; set; }
        public string MeasureSubGroupName { get; set; }
        public Nullable<short> MeasureId { get; set; }
        public Nullable<int> Multiplier { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ACT_BDG_IND { get; set; }
    }
}
