//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIMPRODUCT_20160909
    {
        public int RowID { get; set; }
        public Nullable<short> ProductID { get; set; }
        public string Product { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public string ProductLabel { get; set; }
    }
}
