//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimQtr_bkp
    {
        public int RowID { get; set; }
        public Nullable<short> QtrID { get; set; }
        public Nullable<System.DateTime> Qtr { get; set; }
        public string QtrLabel { get; set; }
        public Nullable<short> SortOrder { get; set; }
    }
}
