//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class dimReportMaster
    {
        public int RowID { get; set; }
        public string ReportCategory { get; set; }
        public string ReportName { get; set; }
        public int ReportOrder { get; set; }
        public int RegionId { get; set; }
        public int ProductId { get; set; }
        public string QTD_YTD_ITD { get; set; }
        public string ReportPageName { get; set; }
        public string ReportHeading { get; set; }
        public Nullable<bool> MGT_RPT_IND { get; set; }
        public Nullable<bool> DAC_RPT_IND { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
