//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCLUSION_MEASURE
    {
        public int RowId { get; set; }
        public Nullable<int> MeasureId { get; set; }
        public string Measure { get; set; }
        public string SrcMeasureAlias { get; set; }
    }
}
