//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAndDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_rights
    {
        public short GROUP_RIGHTS_ID { get; set; }
        public string GROUP_RIGHTS_NAME { get; set; }
    }
}
