//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAndDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public short GROUP_ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public short CREATED_BY_ID { get; set; }
        public short MODIFIED_BY_ID { get; set; }
    }
}
