//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAndDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectActualData
    {
        public long ErrorLogID { get; set; }
        public Nullable<long> RowID { get; set; }
        public string Qtr { get; set; }
        public string Region { get; set; }
        public string Product { get; set; }
        public string Measure { get; set; }
        public string TranType { get; set; }
        public string AmountType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> QtrID { get; set; }
        public Nullable<long> RegionID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> MeasureID { get; set; }
        public Nullable<long> JobID { get; set; }
    }
}
