//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_comments
    {
        public int RowID { get; set; }
        public Nullable<short> qtrID { get; set; }
        public string pagename { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<short> CREATED_BY_ID { get; set; }
        public Nullable<short> MODIFIED_BY_ID { get; set; }
    }
}
