//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAndDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_Headcount
    {
        public int RowID { get; set; }
        public string Location { get; set; }
        public Nullable<short> QtrId { get; set; }
        public Nullable<int> Actual { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<short> SortOrder { get; set; }
    }
}
