//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAndDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_FINANCIALS
    {
        public int Row_id { get; set; }
        public string Region { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public string Measure { get; set; }
        public string Type_ABF { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Product { get; set; }
    }
}
