//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAndDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_ADJUSTMENTS_ISA
    {
        public int RowID { get; set; }
        public Nullable<short> RegionID { get; set; }
        public Nullable<short> ProductID { get; set; }
        public Nullable<short> QtrID { get; set; }
        public Nullable<short> MeasureID { get; set; }
        public string ACT_BDG_IND { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Comments { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
