//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAndDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_ETL_Logs
    {
        public int RowID { get; set; }
        public int JobID { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public string ProcessType { get; set; }
        public string ProcessStatus { get; set; }
        public string ProcessLogMessage { get; set; }
        public string LogUser { get; set; }
        public Nullable<System.DateTime> LogTimestamp { get; set; }
    }
}
