//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_Actuals
    {
        public int RowID { get; set; }
        public string Qtr { get; set; }
        public string Region { get; set; }
        public string Product { get; set; }
        public string Measure { get; set; }
        public string TranType { get; set; }
        public string AmountType { get; set; }
        public string Amount { get; set; }
        public string Comments { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
    }
}
