//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ADJUSTMENTREPORT
    {
        public Nullable<System.DateTime> Qtr { get; set; }
        public string Region { get; set; }
        public string Product { get; set; }
        public string ACCOUNT { get; set; }
        public Nullable<decimal> AdjAmount { get; set; }
        public decimal OriginalAmount { get; set; }
        public string Reason { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> ADJ_DATE { get; set; }
        public string CLASS { get; set; }
    }
}
